services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8050:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
